HHVM_EXT_OPTION(BDB BDB)

if (BDB_INCLUDE_DIRS AND
    BDB_LIBRARIES)
	HHVM_EXTENSION(bdb bdb_common.cpp)
	HHVM_EXTENSION(bdb ext_bdb.cpp)
	HHVM_SYSTEMLIB(bdb ext_bdb.php)
	HHVM_ADD_INCLUDES(bdb ${BDB_INCLUDE_DIRS})
	HHVM_LINK_LIBRARIES(bdb ${BDB_LIBRARIES})
endif()

