HHVM_EXT_OPTION(LMDB LMDB)

if (LMDB_INCLUDE_DIRS AND
    LMDB_LIBRARIES)
	HHVM_EXTENSION(lmdb lmdb_common.cpp)
	HHVM_EXTENSION(lmdb ext_lmdb.cpp)
	HHVM_SYSTEMLIB(lmdb ext_lmdb.php)
	HHVM_ADD_INCLUDES(lmdb ${LMDB_INCLUDE_DIRS})
	HHVM_LINK_LIBRARIES(lmdb ${LMDB_LIBRARIES})
endif()

