HHVM_EXT_OPTION(GEOIP GeoIP)

if (GEOIP_INCLUDE_DIRS AND
    GEOIP_LIBRARIES)
	HHVM_EXTENSION(geoip ext_geoip.cpp)
	HHVM_SYSTEMLIB(geoip ext_geoip.php)
	HHVM_ADD_INCLUDES(geoip ${GEOIP_INCLUDE_DIRS})
	HHVM_LINK_LIBRARIES(geoip ${GEOIP_LIBRARIES})

        HHVM_DEFINE(geoip "-DLIBGEOIP_VERSION=${GEOIP_VERSION}")
        if (GEOIP_HAVE_CUSTOM_DIRECTORY)
          HHVM_DEFINE(geoip "-DHAVE_CUSTOM_DIRECTORY")
        endif()
endif()

