find_package(PkgConfig)
pkg_check_modules(PC_GEOIP geoip>=1.4)

find_path(GEOIP_INCLUDE_DIRS NAMES GeoIP.h
  HINTS ${PC_GEOIP_INCLUDEDIR} ${PC_GEOIP_INCLUDE_DIRS})

find_library(GEOIP_LIBRARIES NAMES GeoIP)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GeoIP DEFAULT_MSG
  GEOIP_LIBRARIES
  GEOIP_INCLUDE_DIRS)

string(REGEX REPLACE "^([0-9]+)\\..*$" "\\1"
  GEOIP_VERSION_MAJOR "${PC_GEOIP_VERSION}")
string(REGEX REPLACE "^[0-9]+\\.([0-9]+)\\..*$" "\\1"
  GEOIP_VERSION_MINOR "${PC_GEOIP_VERSION}")
string(REGEX REPLACE "^[0-9]+\\.[0-9]+\\.([0-9]+).*$" "\\1"
  GEOIP_VERSION_PATCH "${PC_GEOIP_VERSION}")
math(EXPR GEOIP_VERSION
  "${GEOIP_VERSION_MAJOR} * 1000000 + ${GEOIP_VERSION_MINOR} * 1000 + ${GEOIP_VERSION_PATCH}")

include(CheckLibraryExists)
include(CheckSymbolExists)
CHECK_LIBRARY_EXISTS(GeoIP GeoIP_setup_custom_directory ""
  GEOIP_HAVE_CUSTOM_DIRECTORY)
#CHECK_LIBRARY_EXISTS(GeoIP GeoIP_set_charset ""
#  GEOIP_HAVE_SET_CHARSET)
#CHECK_LIBRARY_EXISTS(GeoIP GeoIP_addr_to_num ""
#  GEOIP_HAVE_ADDR_TO_NUM)
#CHECK_SYMBOL_EXISTS(GEOIP_NETSPEED_EDITION_REV1 "GeoIP.h"
#  GEOIP_HAVE_GEOIP_NETSPEED_EDITION_REV1)
#CHECK_SYMBOL_EXISTS(GEOIP_ACCURACYRADIUS_EDITION "GeoIP.h"
#  GEOIP_GEOIP_ACCURACYRADIUS_EDITION)

mark_as_advanced(
  GEOIP_INCLUDE_DIRS
  GEOIP_LIBRARIES
  GEOIP_HAVE_CUSTOM_DIRECTORY)
