if (BDB_LIBRARIES AND BDB_INCLUDE_DIRS)
	set (BDB_FIND_QUIETLY TRUE)
endif (BDB_LIBRARIES AND BDB_INCLUDE_DIRS)

find_path(BDB_INCLUDE_DIRS NAMES db.h)
find_library(BDB_LIBRARIES NAMES db-5.1)

include (FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(BDB DEFAULT_MSG
  BDB_LIBRARIES
  BDB_INCLUDE_DIRS)

mark_as_advanced(BDB_INCLUDE_DIRS BDB_LIBRARIES)
