if (LMDB_LIBRARIES AND LMDB_INCLUDE_DIRS)
	set (LMDB_FIND_QUIETLY TRUE)
endif (LMDB_LIBRARIES AND LMDB_INCLUDE_DIRS)

find_path(LMDB_INCLUDE_DIRS NAMES lmdb.h)
find_library(LMDB_LIBRARIES NAMES lmdb)

include (FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LMDB DEFAULT_MSG
  LMDB_LIBRARIES
  LMDB_INCLUDE_DIRS)

mark_as_advanced(LMDB_INCLUDE_DIRS LMDB_LIBRARIES)
